defaults: &defaults
	twitter:
		clientId: "l4lJEPoAUDZYgrLvOr5J1VNIS"
		clientSecret: "YdcUM6POkXfl4UuQ9Cicn4FJNKTMZY8J1GZDIfTcaWgq9yHQ28"

development:
	<<: *defaults

test:
	<<: *defaults

production:
	<<: *defaults
